### ISSUE TITLE
Hard coded email

### ISSUE THREAD

**Issue by brancusi** [drone-plugins/drone-gcr#1]
Hi,

Wondering what the email here is for:

```
cmd := exec.Command("/usr/bin/docker", "login", "-u", "_json_key", "-p", vargs.Token, "-e", "chunkylover53@aol.com", vargs.Registry)
```

Thanks

**Comment by bradrydzewski** [comment]
Per the documentation the google container registry ignores the email address. The docker client, however, requires a valid email address. Therefore the docs instruct to use any valid email address:

> Unused, must be a well-formed email address (e.g 1234@5678.com).

For these sort of questions feel free to use our discussion forum or chat room and to reserve issues trackers for bugs and feature requests. Thanks!

[1] https://cloud.google.com/container-registry/docs/auth#using_a_json_key_file
