### ISSUE TITLE
why is chunkylover@aol.com hard-coded into the docker login email flag?

### ISSUE THREAD

**Issue by pgruenbacher** [drone-plugins/drone-gcr#6]

**Comment by gtaylor** [comment]
Maybe an ill-advised value, but the email param is ignored for GCR.

**Comment by tboerger** [comment]
https://github.com/drone-plugins/drone-gcr/issues/1 for reference

**Comment by pgruenbacher** [comment]
thanks, didn't think to check previous issues. very much enjoying using drone.io
